# Treccani validation of Cultura

## Settings

In [1]:
from pathlib import Path
import re

import duckdb
import pandas as pd

ROOT = Path.cwd().parent
AI_ANSWERS = ROOT / "annotations" / "treccani_validation" / "treccani_ai_annotations_cultura289.parquet"
DATABASE = ROOT / "data" / "cultura" / "humans_clean_v2_sample_treccani.duckdb"

## Treccani answers found by the AI

In [2]:
def window_years(answer):
    years = []
    for year, decade in re.findall(r"\b(\d{3,4})(s?)\b", answer or ""):
        years += [int(year), int(year) + 9] if decade else [int(year)]
    if years:
        return min(years), max(years)
    centuries = [int(c) for c in re.findall(r"(\d{1,2})(?:st|nd|rd|th) century", answer or "")]
    if centuries:
        return (min(centuries) - 1) * 100 + 1, max(centuries) * 100
    return None, None


raw = pd.read_parquet(AI_ANSWERS)
treccani = pd.DataFrame({
    "qid": raw["entity"].map(lambda entity: entity["qid"]),
    "name": raw["entity"].map(lambda entity: entity["label_en"]),
    "treccani_polity": raw["polity_ai_matched"].map(lambda answer: answer["answer"]),
    "treccani_polity_id": raw["polity_ai_matched"].map(lambda answer: int(answer["source_verbatim"][0].split("|")[0]) if len(answer["source_verbatim"]) else None),
    "treccani_window": raw["productivity_window_ai_extracted"].map(lambda answer: answer["answer"]),
})
treccani[["treccani_start", "treccani_end"]] = treccani["treccani_window"].map(window_years).tolist()
assert treccani["qid"].is_unique
print(len(treccani), "individuals")
treccani

50 individuals

,qid,name,treccani_polity,treccani_polity_id,treccani_window,treccani_start,treccani_end
0,Q16577209,Maurizio Cattaneo,Republic of Genoa,589.0,1451-1484,1451,1484
1,Q109861078,Olimpio Cozzolino,Kingdom of Italy,350.0,1894-1937,1894,1937
2,Q3607061,Aicone,Kingdom of Italy,350.0,905-915,905,915
3,Q318593,Girolamo Fracastoro,Republic of Venice,397.0,before 1502 to 1553,1502,1553
4,Q26997486,Bartolo da San Gimignano,Holy Roman Empire Minor States,783.0,1293,1293,1293
5,Q18758541,Domenico Forges Davanzati,Kingdom of Naples (Napoleonic),1140.0,1768-1809,1768,1809
6,Q15428551,Biagio Buonaccorsi,Republic of Florence,768.0,1498-1512,1498,1512
7,Q95387776,Carbone Malocello,Republic of Genoa,589.0,1216-1235,1216,1235
8,Q1399161,Fazio of Uberti,Holy Roman Empire,1612.0,from the 1330s to the late 1350s,1330,1359
9,Q53004,Vittorio De Sica,Republic of Italy,1428.0,1923-1974,1923,1974
10,Q112842831,Giacinto Maselli,Papal States,419.0,around 1665 - 1702,1665,1702
11,Q1118036,Giovanni Francesco Grossi,Papal States,419.0,1671-1697,1671,1697
12,Q1495278,Gaspare Firriolo,Kingdom of the Two Sicilies,1238.0,between the mid-18th century and the first dec...,1701,1900
13,Q264271,Pietro Ranzano,Crown of Aragon,699.0,from around 1440 to 1491,1440,1491
14,Q3034728,Domenico Del Frate,Papal States,419.0,1787-1821,1787,1821
15,Q785349,Cangrande I della Scala,Holy Roman Empire Minor States,783.0,1307-1328,1307,1328
16,Q110215095,Enrico Altan,Republic of Venice,397.0,1601-1633,1601,1633
17,Q98960294,Giacomo Zane,Republic of Venice,397.0,1552-1560,1552,1560
18,Q2294640,Pasquale Cafaro,Kingdom of Naples (Napoleonic),1140.0,1744-1785,1744,1785
19,Q50330355,Francesco Ponzio,Spanish Empire,1622.0,1589-1604,1589,1604
20,Q266497,Martinus Gosia,Papal States,419.0,starting from 1125,1125,1125
21,Q55227668,Giovanni Francesco Fiori,Papal States,419.0,1739-1783,1739,1783
22,Q3608762,Angelo Tartaglia,Papal States,419.0,1402-1421,1402,1421
23,Q106864124,Lucio Domizio Brusoni,Papal States,419.0,second decade of the 16th century,1501,1600
24,Q20140247,Uguccione dei Contrari,Papal States,419.0,1402-1448,1402,1448
25,Q3766787,Giovanni Battista Del Tufo,Spanish Empire,1622.0,1571 - early 17th century,1571,1571
26,Q19823036,Taddeo Garganelli,Papal States,419.0,1445-1466,1445,1466
27,Q26246988,Nicola Paglia,Papal States,419.0,1220-1255,1220,1255
28,Q3765441,Giorgio Falco,Republic of Italy,1428.0,central decades of the 20th century,1901,2000
29,Q3876135,Nicola Bonservizi,French Third Republic,1634.0,1912-1924,1912,1924
30,Q1525438,Giorgio Colli,Republic of Italy,1428.0,1949-1979,1949,1979
31,Q3839143,Ludovico Seitz,Papal States,419.0,since 1860,1860,1860
32,Q3767458,Giovanni Guidiccioni,Papal States,419.0,1525-1541,1525,1541
33,Q3436971,Roberto Sanseverino d'Aragona,Duchy of Milan,923.0,1447-1485,1447,1485
34,Q1144617,Angelo Oliviero Olivetti,Kingdom of Italy,350.0,1892-1931,1892,1931
35,Q59630395,Giovanni Giacomo Caroldo,Republic of Venice,397.0,around 1496 - 1532,1496,1532
36,Q935635,Otto Orseolo,Republic of Venice,397.0,1007-1026,1007,1026
37,Q171807,Nilus the Younger,Byzantine Empire,373.0,mid-10th century to 1004,1004,1004
38,Q3875919,NiccolÃ² di Buonaccorso,NaN,NaN,second half of the 14th century,1301,1400
39,Q1369480,Ruggiero Giovannelli,Papal States,419.0,1582-1625,1582,1625
40,Q97974535,Fino d'Arezzo,Papal States,419.0,1292 and between the 13th and 14th century,1292,1292
41,Q3627864,Athanasius I,Duchy of Naples,422.0,849-872,849,872
42,Q3839885,Luigi Messedaglia,Kingdom of Italy,350.0,1898-1956,1898,1956
43,Q2262015,Luca Gaurico,Papal States,419.0,1501-1550,1501,1550
44,Q12900989,Maino De Maineri,Holy Roman Empire Minor States,783.0,around 1323 - 1364,1323,1364
45,Q1154997,Giovanni di Matera,Norman Italy,608.0,around 1100-1110 to 1139,1100,1139
46,Q27553577,Bongiovanni da Cavriana,Holy Roman Empire,523.0,between the third and fifth decade of the 13th...,1201,1300
47,Q3622896,Armando Brasini,Kingdom of Italy,350.0,years around 1930,1930,1930
48,Q1525792,Giovanni Battista Abiosi,Kingdom of Naples,798.0,late 15th to early 16th century,1501,1600
49,Q5565320,Giuseppe Agnelli,Papal States,419.0,1637-1703,1637,1703

## Cultura window and polities

In [3]:
connection = duckdb.connect(str(DATABASE), read_only=True)
qids = treccani["qid"].tolist()

windows = connection.execute("""
    SELECT individual_enriched.entity.qid AS qid,
           individual_enriched.peak_productivity.start_year AS cultura_start,
           individual_enriched.peak_productivity.end_year AS cultura_end
    FROM individual_enriched
    WHERE individual_enriched.entity.qid IN (SELECT unnest(?))
""", [qids]).df()
windows["cultura_window"] = windows.apply(lambda row: None if pd.isna(row["cultura_start"]) else f"{int(row['cultura_start'])}-{int(row['cultura_end'])}", axis=1)

sub_polities = connection.execute("""
    SELECT individual_enriched.entity.qid AS qid,
           list(polity_match.polity.cliopatria_id) AS cultura_sub_polity_ids,
           string_agg(polity_match.polity.name, ' / ') AS cultura_sub_polities
    FROM individual_enriched, unnest(individual_enriched.polity) AS unnested(polity_match)
    WHERE individual_enriched.entity.qid IN (SELECT unnest(?))
    GROUP BY qid
""", [qids]).df()

meta_polities = connection.execute("""
    SELECT individual_enriched.entity.qid AS qid,
           list(DISTINCT meta.cliopatria_id) AS cultura_meta_polity_ids,
           string_agg(DISTINCT meta.name, ' / ') AS cultura_meta_polities
    FROM individual_enriched,
         unnest(individual_enriched.polity) AS unnested(polity_match),
         unnest(polity_match.polity.meta_polities) AS unnested_meta(meta)
    WHERE individual_enriched.entity.qid IN (SELECT unnest(?))
      AND meta.start_year <= individual_enriched.peak_productivity.end_year
      AND meta.end_year >= individual_enriched.peak_productivity.start_year
    GROUP BY qid
""", [qids]).df()

cultura = windows.merge(sub_polities, on="qid", how="left").merge(meta_polities, on="qid", how="left")
print(len(cultura), "individuals,", cultura["cultura_sub_polities"].notna().sum(), "with a polity")
cultura

50 individuals, 50 with a polity

,qid,cultura_start,cultura_end,cultura_window,cultura_sub_polity_ids,cultura_sub_polities,cultura_meta_polity_ids,cultura_meta_polities
0,Q26997486,1261,1274,1261-1274,[768],Republic of Florence,[1612],Holy Roman Empire
1,Q109861078,1898,1922,1898-1922,[350],Kingdom of Italy,NaN,NaN
2,Q3607061,904,918,904-918,"[350, 500]",Kingdom of Italy / Kingdom of Lower Burgundy,[1611],Carolingian Empire
3,Q318593,1507,1528,1507-1528,[397],Republic of Venice,NaN,NaN
4,Q3627864,852,871,852-871,[422],Duchy of Naples,NaN,NaN
5,Q50330355,1598,1604,1598-1604,[1043],Iberian Union,[1622],Spanish Empire
6,Q3436971,1448,1463,1448-1463,[923],Duchy of Milan,[1612],Holy Roman Empire
7,Q97974535,1300,1322,1300-1322,[768],Republic of Florence,[1612],Holy Roman Empire
8,Q27553577,1270,1294,1270-1294,[783],Holy Roman Empire Minor States,[1612],Holy Roman Empire
9,Q26246988,1238,1246,1238-1246,[523],Holy Roman Empire,[1612],Holy Roman Empire
10,Q5565320,1647,1683,1647-1683,[419],Papal States,NaN,NaN
11,Q98960294,1557,1560,1557-1560,[397],Republic of Venice,NaN,NaN
12,Q2262015,1505,1526,1505-1526,[419],Papal States,NaN,NaN
13,Q18758541,1777,1788,1777-1788,"[1140, 1000]",Kingdom of Naples (Napoleonic) / Kingdom of Spain,[1622],Spanish Empire
14,Q112842831,1669,1694,1669-1694,[1000],Kingdom of Spain,[1622],Spanish Empire
15,Q95387776,1223,1235,1223-1235,[589],Republic of Genoa,NaN,NaN
16,Q2294640,1745,1762,1745-1762,"[1000, 1140]",Kingdom of Spain / Kingdom of Naples (Napoleonic),[1622],Spanish Empire
17,Q20140247,1408,1417,1408-1417,[419],Papal States,NaN,NaN
18,Q3839143,1877,1902,1877-1902,[350],Kingdom of Italy,NaN,NaN
19,Q3839885,1912,1929,1912-1929,[350],Kingdom of Italy,NaN,NaN
20,Q264271,1458,1479,1458-1479,"[798, 699]",Kingdom of Naples / Crown of Aragon,[975],Personal union of Crown of Aragon with Crown o...
21,Q53004,1940,1974,1940-1974,[1428],Republic of Italy,NaN,NaN
22,Q1144617,1911,1931,1911-1931,[350],Kingdom of Italy,NaN,NaN
23,Q19823036,1460,1469,1460-1469,[419],Papal States,NaN,NaN
24,Q3876135,1918,1924,1918-1924,[1332],French Third Republic,[1634],French Third Republic
25,Q12900989,1480,1507,1480-1507,[419],Papal States,NaN,NaN
26,Q1399161,1400,1422,1400-1422,"[397, 783]",Republic of Venice / Holy Roman Empire Minor S...,[1612],Holy Roman Empire
27,Q1118036,1684,1697,1684-1697,[419],Papal States,NaN,NaN
28,Q110215095,1601,1622,1601-1622,[397],Republic of Venice,NaN,NaN
29,Q1369480,1851,1876,1851-1876,"[419, 350]",Papal States / Kingdom of Italy,NaN,NaN
30,Q3034728,1805,1829,1805-1829,"[419, 1189]",Papal States / First French Empire,[1629],First French Empire
31,Q1525792,1502,1523,1502-1523,"[699, 1000, 570]",Crown of Aragon / Kingdom of Spain / Kingdom o...,"[975, 1616, 1622]",Kingdom of France / Spanish Empire / Personal ...
32,Q3622896,1907,1931,1907-1931,[350],Kingdom of Italy,NaN,NaN
33,Q785349,1321,1329,1321-1329,[783],Holy Roman Empire Minor States,[1612],Holy Roman Empire
34,Q1495278,1760,1777,1760-1777,"[1000, 1140]",Kingdom of Spain / Kingdom of Naples (Napoleonic),[1622],Spanish Empire
35,Q3608762,1399,1408,1399-1408,[768],Republic of Florence,[1612],Holy Roman Empire
36,Q59630395,1508,1538,1508-1538,[397],Republic of Venice,NaN,NaN
37,Q3767458,1600,1994,1600-1994,"[419, 350, 1428, 1184, 1189, 1115, 1170, 1412]",Papal States / Kingdom of Italy / Republic of ...,"[1031, 1629]",First French Empire / Alliance between Papal S...
38,Q16577209,1431,1446,1431-1446,[589],Republic of Genoa,NaN,NaN
39,Q106864124,1600,1600,1600-1600,[1043],Iberian Union,[1622],Spanish Empire
40,Q1154997,1106,1116,1106-1116,[608],Norman Italy,NaN,NaN
41,Q266497,1136,1146,1136-1146,[523],Holy Roman Empire,[1612],Holy Roman Empire
42,Q935635,1027,1032,1027-1032,[397],Republic of Venice,NaN,NaN
43,Q3875919,1377,1388,1377-1388,[783],Holy Roman Empire Minor States,[1612],Holy Roman Empire
44,Q1525438,1969,2010,1969-2010,[1428],Republic of Italy,NaN,NaN
45,Q171807,939,953,939-953,[373],Byzantine Empire,NaN,NaN
46,Q15428551,1496,1526,1496-1526,[768],Republic of Florence,NaN,NaN
47,Q3765441,1926,1943,1926-1943,[350],Kingdom of Italy,NaN,NaN
48,Q3766787,1579,1594,1579-1594,"[1043, 1000]",Iberian Union / Kingdom of Spain,[1622],Spanish Empire
49,Q55227668,1738,1761,1738-1761,[419],Papal States,NaN,NaN

## Comparison table

In [4]:
comparison = treccani.merge(cultura, on="qid", how="left")
assert len(comparison) == len(treccani)
comparison

,qid,name,treccani_polity,treccani_polity_id,treccani_window,treccani_start,treccani_end,cultura_start,cultura_end,cultura_window,cultura_sub_polity_ids,cultura_sub_polities,cultura_meta_polity_ids,cultura_meta_polities
0,Q16577209,Maurizio Cattaneo,Republic of Genoa,589.0,1451-1484,1451,1484,1431,1446,1431-1446,[589],Republic of Genoa,NaN,NaN
1,Q109861078,Olimpio Cozzolino,Kingdom of Italy,350.0,1894-1937,1894,1937,1898,1922,1898-1922,[350],Kingdom of Italy,NaN,NaN
2,Q3607061,Aicone,Kingdom of Italy,350.0,905-915,905,915,904,918,904-918,"[350, 500]",Kingdom of Italy / Kingdom of Lower Burgundy,[1611],Carolingian Empire
3,Q318593,Girolamo Fracastoro,Republic of Venice,397.0,before 1502 to 1553,1502,1553,1507,1528,1507-1528,[397],Republic of Venice,NaN,NaN
4,Q26997486,Bartolo da San Gimignano,Holy Roman Empire Minor States,783.0,1293,1293,1293,1261,1274,1261-1274,[768],Republic of Florence,[1612],Holy Roman Empire
5,Q18758541,Domenico Forges Davanzati,Kingdom of Naples (Napoleonic),1140.0,1768-1809,1768,1809,1777,1788,1777-1788,"[1140, 1000]",Kingdom of Naples (Napoleonic) / Kingdom of Spain,[1622],Spanish Empire
6,Q15428551,Biagio Buonaccorsi,Republic of Florence,768.0,1498-1512,1498,1512,1496,1526,1496-1526,[768],Republic of Florence,NaN,NaN
7,Q95387776,Carbone Malocello,Republic of Genoa,589.0,1216-1235,1216,1235,1223,1235,1223-1235,[589],Republic of Genoa,NaN,NaN
8,Q1399161,Fazio of Uberti,Holy Roman Empire,1612.0,from the 1330s to the late 1350s,1330,1359,1400,1422,1400-1422,"[397, 783]",Republic of Venice / Holy Roman Empire Minor S...,[1612],Holy Roman Empire
9,Q53004,Vittorio De Sica,Republic of Italy,1428.0,1923-1974,1923,1974,1940,1974,1940-1974,[1428],Republic of Italy,NaN,NaN
10,Q112842831,Giacinto Maselli,Papal States,419.0,around 1665 - 1702,1665,1702,1669,1694,1669-1694,[1000],Kingdom of Spain,[1622],Spanish Empire
11,Q1118036,Giovanni Francesco Grossi,Papal States,419.0,1671-1697,1671,1697,1684,1697,1684-1697,[419],Papal States,NaN,NaN
12,Q1495278,Gaspare Firriolo,Kingdom of the Two Sicilies,1238.0,between the mid-18th century and the first dec...,1701,1900,1760,1777,1760-1777,"[1000, 1140]",Kingdom of Spain / Kingdom of Naples (Napoleonic),[1622],Spanish Empire
13,Q264271,Pietro Ranzano,Crown of Aragon,699.0,from around 1440 to 1491,1440,1491,1458,1479,1458-1479,"[798, 699]",Kingdom of Naples / Crown of Aragon,[975],Personal union of Crown of Aragon with Crown o...
14,Q3034728,Domenico Del Frate,Papal States,419.0,1787-1821,1787,1821,1805,1829,1805-1829,"[419, 1189]",Papal States / First French Empire,[1629],First French Empire
15,Q785349,Cangrande I della Scala,Holy Roman Empire Minor States,783.0,1307-1328,1307,1328,1321,1329,1321-1329,[783],Holy Roman Empire Minor States,[1612],Holy Roman Empire
16,Q110215095,Enrico Altan,Republic of Venice,397.0,1601-1633,1601,1633,1601,1622,1601-1622,[397],Republic of Venice,NaN,NaN
17,Q98960294,Giacomo Zane,Republic of Venice,397.0,1552-1560,1552,1560,1557,1560,1557-1560,[397],Republic of Venice,NaN,NaN
18,Q2294640,Pasquale Cafaro,Kingdom of Naples (Napoleonic),1140.0,1744-1785,1744,1785,1745,1762,1745-1762,"[1000, 1140]",Kingdom of Spain / Kingdom of Naples (Napoleonic),[1622],Spanish Empire
19,Q50330355,Francesco Ponzio,Spanish Empire,1622.0,1589-1604,1589,1604,1598,1604,1598-1604,[1043],Iberian Union,[1622],Spanish Empire
20,Q266497,Martinus Gosia,Papal States,419.0,starting from 1125,1125,1125,1136,1146,1136-1146,[523],Holy Roman Empire,[1612],Holy Roman Empire
21,Q55227668,Giovanni Francesco Fiori,Papal States,419.0,1739-1783,1739,1783,1738,1761,1738-1761,[419],Papal States,NaN,NaN
22,Q3608762,Angelo Tartaglia,Papal States,419.0,1402-1421,1402,1421,1399,1408,1399-1408,[768],Republic of Florence,[1612],Holy Roman Empire
23,Q106864124,Lucio Domizio Brusoni,Papal States,419.0,second decade of the 16th century,1501,1600,1600,1600,1600-1600,[1043],Iberian Union,[1622],Spanish Empire
24,Q20140247,Uguccione dei Contrari,Papal States,419.0,1402-1448,1402,1448,1408,1417,1408-1417,[419],Papal States,NaN,NaN
25,Q3766787,Giovanni Battista Del Tufo,Spanish Empire,1622.0,1571 - early 17th century,1571,1571,1579,1594,1579-1594,"[1043, 1000]",Iberian Union / Kingdom of Spain,[1622],Spanish Empire
26,Q19823036,Taddeo Garganelli,Papal States,419.0,1445-1466,1445,1466,1460,1469,1460-1469,[419],Papal States,NaN,NaN
27,Q26246988,Nicola Paglia,Papal States,419.0,1220-1255,1220,1255,1238,1246,1238-1246,[523],Holy Roman Empire,[1612],Holy Roman Empire
28,Q3765441,Giorgio Falco,Republic of Italy,1428.0,central decades of the 20th century,1901,2000,1926,1943,1926-1943,[350],Kingdom of Italy,NaN,NaN
29,Q3876135,Nicola Bonservizi,French Third Republic,1634.0,1912-1924,1912,1924,1918,1924,1918-1924,[1332],French Third Republic,[1634],French Third Republic
30,Q1525438,Giorgio Colli,Republic of Italy,1428.0,1949-1979,1949,1979,1969,2010,1969-2010,[1428],Republic of Italy,NaN,NaN
31,Q3839143,Ludovico Seitz,Papal States,419.0,since 1860,1860,1860,1877,1902,1877-1902,[350],Kingdom of Italy,NaN,NaN
32,Q3767458,Giovanni Guidiccioni,Papal States,419.0,1525-1541,1525,1541,1600,1994,1600-1994,"[419, 350, 1428, 1184, 1189, 1115, 1170, 1412]",Papal States / Kingdom of Italy / Republic of ...,"[1031, 1629]",First French Empire / Alliance between Papal S...
33,Q3436971,Roberto Sanseverino d'Aragona,Duchy of Milan,923.0,1447-1485,1447,1485,1448,1463,1448-1463,[923],Duchy of Milan,[1612],Holy Roman Empire
34,Q1144617,Angelo Oliviero Olivetti,Kingdom of Italy,350.0,1892-1931,1892,1931,1911,1931,1911-1931,[350],Kingdom of Italy,NaN,NaN
35,Q59630395,Giovanni Giacomo Caroldo,Republic of Venice,397.0,around 1496 - 1532,1496,1532,1508,1538,1508-1538,[397],Republic of Venice,NaN,NaN
36,Q935635,Otto Orseolo,Republic of Venice,397.0,1007-1026,1007,1026,1027,1032,1027-1032,[397],Republic of Venice,NaN,NaN
37,Q171807,Nilus the Younger,Byzantine Empire,373.0,mid-10th century to 1004,1004,1004,939,953,939-953,[373],Byzantine Empire,NaN,NaN
38,Q3875919,NiccolÃ² di Buonaccorso,NaN,NaN,second half of the 14th century,1301,1400,1377,1388,1377-1388,[783],Holy Roman Empire Minor States,[1612],Holy Roman Empire
39,Q1369480,Ruggiero Giovannelli,Papal States,419.0,1582-1625,1582,1625,1851,1876,1851-1876,"[419, 350]",Papal States / Kingdom of Italy,NaN,NaN
40,Q97974535,Fino d'Arezzo,Papal States,419.0,1292 and between the 13th and 14th century,1292,1292,1300,1322,1300-1322,[768],Republic of Florence,[1612],Holy Roman Empire
41,Q3627864,Athanasius I,Duchy of Naples,422.0,849-872,849,872,852,871,852-871,[422],Duchy of Naples,NaN,NaN
42,Q3839885,Luigi Messedaglia,Kingdom of Italy,350.0,1898-1956,1898,1956,1912,1929,1912-1929,[350],Kingdom of Italy,NaN,NaN
43,Q2262015,Luca Gaurico,Papal States,419.0,1501-1550,1501,1550,1505,1526,1505-1526,[419],Papal States,NaN,NaN
44,Q12900989,Maino De Maineri,Holy Roman Empire Minor States,783.0,around 1323 - 1364,1323,1364,1480,1507,1480-1507,[419],Papal States,NaN,NaN
45,Q1154997,Giovanni di Matera,Norman Italy,608.0,around 1100-1110 to 1139,1100,1139,1106,1116,1106-1116,[608],Norman Italy,NaN,NaN
46,Q27553577,Bongiovanni da Cavriana,Holy Roman Empire,523.0,between the third and fifth decade of the 13th...,1201,1300,1270,1294,1270-1294,[783],Holy Roman Empire Minor States,[1612],Holy Roman Empire
47,Q3622896,Armando Brasini,Kingdom of Italy,350.0,years around 1930,1930,1930,1907,1931,1907-1931,[350],Kingdom of Italy,NaN,NaN
48,Q1525792,Giovanni Battista Abiosi,Kingdom of Naples,798.0,late 15th to early 16th century,1501,1600,1502,1523,1502-1523,"[699, 1000, 570]",Crown of Aragon / Kingdom of Spain / Kingdom o...,"[975, 1616, 1622]",Kingdom of France / Spanish Empire / Personal ...
49,Q5565320,Giuseppe Agnelli,Papal States,419.0,1637-1703,1637,1703,1647,1683,1647-1683,[419],Papal States,NaN,NaN

## Polity accuracy

In [5]:
as_list = lambda ids: [] if ids is None or isinstance(ids, float) else list(ids)
names = lambda text: [] if not isinstance(text, str) else [name.strip() for name in text.split(" / ")]
sub_ids = comparison["cultura_sub_polity_ids"].map(as_list)
meta_ids = comparison["cultura_meta_polity_ids"].map(as_list)
sub_names = comparison["cultura_sub_polities"].map(names)
meta_names = comparison["cultura_meta_polities"].map(names)
comparison["polity_match"] = [
    "sub polity" if treccani_id in subs or treccani_name in sub_name_list else
    "meta polity" if treccani_id in metas or treccani_name in meta_name_list else "none"
    for treccani_id, treccani_name, subs, metas, sub_name_list, meta_name_list
    in zip(comparison["treccani_polity_id"], comparison["treccani_polity"], sub_ids, meta_ids, sub_names, meta_names)
]
comparison["polity_ok"] = comparison["polity_match"] != "none"
comparison["has_treccani_polity"] = comparison["treccani_polity_id"].notna()
print((~comparison["has_treccani_polity"]).sum(), "individual(s) without a Treccani polity, left out of the polity accuracy")
comparison[["name", "treccani_polity", "cultura_sub_polities", "cultura_meta_polities", "polity_match", "polity_ok"]]

1 individual(s) without a Treccani polity, left out of the polity accuracy

,name,treccani_polity,cultura_sub_polities,cultura_meta_polities,polity_match,polity_ok
0,Maurizio Cattaneo,Republic of Genoa,Republic of Genoa,NaN,sub polity,True
1,Olimpio Cozzolino,Kingdom of Italy,Kingdom of Italy,NaN,sub polity,True
2,Aicone,Kingdom of Italy,Kingdom of Italy / Kingdom of Lower Burgundy,Carolingian Empire,sub polity,True
3,Girolamo Fracastoro,Republic of Venice,Republic of Venice,NaN,sub polity,True
4,Bartolo da San Gimignano,Holy Roman Empire Minor States,Republic of Florence,Holy Roman Empire,none,False
5,Domenico Forges Davanzati,Kingdom of Naples (Napoleonic),Kingdom of Naples (Napoleonic) / Kingdom of Spain,Spanish Empire,sub polity,True
6,Biagio Buonaccorsi,Republic of Florence,Republic of Florence,NaN,sub polity,True
7,Carbone Malocello,Republic of Genoa,Republic of Genoa,NaN,sub polity,True
8,Fazio of Uberti,Holy Roman Empire,Republic of Venice / Holy Roman Empire Minor S...,Holy Roman Empire,meta polity,True
9,Vittorio De Sica,Republic of Italy,Republic of Italy,NaN,sub polity,True
10,Giacinto Maselli,Papal States,Kingdom of Spain,Spanish Empire,none,False
11,Giovanni Francesco Grossi,Papal States,Papal States,NaN,sub polity,True
12,Gaspare Firriolo,Kingdom of the Two Sicilies,Kingdom of Spain / Kingdom of Naples (Napoleonic),Spanish Empire,none,False
13,Pietro Ranzano,Crown of Aragon,Kingdom of Naples / Crown of Aragon,Personal union of Crown of Aragon with Crown o...,sub polity,True
14,Domenico Del Frate,Papal States,Papal States / First French Empire,First French Empire,sub polity,True
15,Cangrande I della Scala,Holy Roman Empire Minor States,Holy Roman Empire Minor States,Holy Roman Empire,sub polity,True
16,Enrico Altan,Republic of Venice,Republic of Venice,NaN,sub polity,True
17,Giacomo Zane,Republic of Venice,Republic of Venice,NaN,sub polity,True
18,Pasquale Cafaro,Kingdom of Naples (Napoleonic),Kingdom of Spain / Kingdom of Naples (Napoleonic),Spanish Empire,sub polity,True
19,Francesco Ponzio,Spanish Empire,Iberian Union,Spanish Empire,meta polity,True
20,Martinus Gosia,Papal States,Holy Roman Empire,Holy Roman Empire,none,False
21,Giovanni Francesco Fiori,Papal States,Papal States,NaN,sub polity,True
22,Angelo Tartaglia,Papal States,Republic of Florence,Holy Roman Empire,none,False
23,Lucio Domizio Brusoni,Papal States,Iberian Union,Spanish Empire,none,False
24,Uguccione dei Contrari,Papal States,Papal States,NaN,sub polity,True
25,Giovanni Battista Del Tufo,Spanish Empire,Iberian Union / Kingdom of Spain,Spanish Empire,meta polity,True
26,Taddeo Garganelli,Papal States,Papal States,NaN,sub polity,True
27,Nicola Paglia,Papal States,Holy Roman Empire,Holy Roman Empire,none,False
28,Giorgio Falco,Republic of Italy,Kingdom of Italy,NaN,none,False
29,Nicola Bonservizi,French Third Republic,French Third Republic,French Third Republic,sub polity,True
30,Giorgio Colli,Republic of Italy,Republic of Italy,NaN,sub polity,True
31,Ludovico Seitz,Papal States,Kingdom of Italy,NaN,none,False
32,Giovanni Guidiccioni,Papal States,Papal States / Kingdom of Italy / Republic of ...,First French Empire / Alliance between Papal S...,sub polity,True
33,Roberto Sanseverino d'Aragona,Duchy of Milan,Duchy of Milan,Holy Roman Empire,sub polity,True
34,Angelo Oliviero Olivetti,Kingdom of Italy,Kingdom of Italy,NaN,sub polity,True
35,Giovanni Giacomo Caroldo,Republic of Venice,Republic of Venice,NaN,sub polity,True
36,Otto Orseolo,Republic of Venice,Republic of Venice,NaN,sub polity,True
37,Nilus the Younger,Byzantine Empire,Byzantine Empire,NaN,sub polity,True
38,NiccolÃ² di Buonaccorso,NaN,Holy Roman Empire Minor States,Holy Roman Empire,none,False
39,Ruggiero Giovannelli,Papal States,Papal States / Kingdom of Italy,NaN,sub polity,True
40,Fino d'Arezzo,Papal States,Republic of Florence,Holy Roman Empire,none,False
41,Athanasius I,Duchy of Naples,Duchy of Naples,NaN,sub polity,True
42,Luigi Messedaglia,Kingdom of Italy,Kingdom of Italy,NaN,sub polity,True
43,Luca Gaurico,Papal States,Papal States,NaN,sub polity,True
44,Maino De Maineri,Holy Roman Empire Minor States,Papal States,NaN,none,False
45,Giovanni di Matera,Norman Italy,Norman Italy,NaN,sub polity,True
46,Bongiovanni da Cavriana,Holy Roman Empire,Holy Roman Empire Minor States,Holy Roman Empire,meta polity,True
47,Armando Brasini,Kingdom of Italy,Kingdom of Italy,NaN,sub polity,True
48,Giovanni Battista Abiosi,Kingdom of Naples,Crown of Aragon / Kingdom of Spain / Kingdom o...,Kingdom of France / Spanish Empire / Personal ...,none,False
49,Giuseppe Agnelli,Papal States,Papal States,NaN,sub polity,True

## Productivity window accuracy

In [6]:
overlap = (comparison[["treccani_end", "cultura_end"]].min(axis=1, skipna=False) - comparison[["treccani_start", "cultura_start"]].max(axis=1, skipna=False) + 1).clip(lower=0)
treccani_span = comparison["treccani_end"] - comparison["treccani_start"] + 1
comparison["overlap_years"] = overlap
comparison["overlap_share"] = (overlap / treccani_span).round(2)
comparison["window_ok"] = comparison["overlap_years"].fillna(0) > 0
comparison["has_treccani_window"] = comparison["treccani_start"].notna()
print((~comparison["has_treccani_window"]).sum(), "individual(s) without a Treccani window, left out of the window accuracy")
print(comparison["cultura_start"].isna().sum(), "individual(s) without a Cultura window, counted as wrong")
comparison[["name", "treccani_window", "cultura_window", "overlap_years", "overlap_share", "window_ok"]]

0 individual(s) without a Treccani window, left out of the window accuracy
0 individual(s) without a Cultura window, counted as wrong

,name,treccani_window,cultura_window,overlap_years,overlap_share,window_ok
0,Maurizio Cattaneo,1451-1484,1431-1446,0,0.00,False
1,Olimpio Cozzolino,1894-1937,1898-1922,25,0.57,True
2,Aicone,905-915,904-918,11,1.00,True
3,Girolamo Fracastoro,before 1502 to 1553,1507-1528,22,0.42,True
4,Bartolo da San Gimignano,1293,1261-1274,0,0.00,False
5,Domenico Forges Davanzati,1768-1809,1777-1788,12,0.29,True
6,Biagio Buonaccorsi,1498-1512,1496-1526,15,1.00,True
7,Carbone Malocello,1216-1235,1223-1235,13,0.65,True
8,Fazio of Uberti,from the 1330s to the late 1350s,1400-1422,0,0.00,False
9,Vittorio De Sica,1923-1974,1940-1974,35,0.67,True
10,Giacinto Maselli,around 1665 - 1702,1669-1694,26,0.68,True
11,Giovanni Francesco Grossi,1671-1697,1684-1697,14,0.52,True
12,Gaspare Firriolo,between the mid-18th century and the first dec...,1760-1777,18,0.09,True
13,Pietro Ranzano,from around 1440 to 1491,1458-1479,22,0.42,True
14,Domenico Del Frate,1787-1821,1805-1829,17,0.49,True
15,Cangrande I della Scala,1307-1328,1321-1329,8,0.36,True
16,Enrico Altan,1601-1633,1601-1622,22,0.67,True
17,Giacomo Zane,1552-1560,1557-1560,4,0.44,True
18,Pasquale Cafaro,1744-1785,1745-1762,18,0.43,True
19,Francesco Ponzio,1589-1604,1598-1604,7,0.44,True
20,Martinus Gosia,starting from 1125,1136-1146,0,0.00,False
21,Giovanni Francesco Fiori,1739-1783,1738-1761,23,0.51,True
22,Angelo Tartaglia,1402-1421,1399-1408,7,0.35,True
23,Lucio Domizio Brusoni,second decade of the 16th century,1600-1600,1,0.01,True
24,Uguccione dei Contrari,1402-1448,1408-1417,10,0.21,True
25,Giovanni Battista Del Tufo,1571 - early 17th century,1579-1594,0,0.00,False
26,Taddeo Garganelli,1445-1466,1460-1469,7,0.32,True
27,Nicola Paglia,1220-1255,1238-1246,9,0.25,True
28,Giorgio Falco,central decades of the 20th century,1926-1943,18,0.18,True
29,Nicola Bonservizi,1912-1924,1918-1924,7,0.54,True
30,Giorgio Colli,1949-1979,1969-2010,11,0.35,True
31,Ludovico Seitz,since 1860,1877-1902,0,0.00,False
32,Giovanni Guidiccioni,1525-1541,1600-1994,0,0.00,False
33,Roberto Sanseverino d'Aragona,1447-1485,1448-1463,16,0.41,True
34,Angelo Oliviero Olivetti,1892-1931,1911-1931,21,0.52,True
35,Giovanni Giacomo Caroldo,around 1496 - 1532,1508-1538,25,0.68,True
36,Otto Orseolo,1007-1026,1027-1032,0,0.00,False
37,Nilus the Younger,mid-10th century to 1004,939-953,0,0.00,False
38,NiccolÃ² di Buonaccorso,second half of the 14th century,1377-1388,12,0.12,True
39,Ruggiero Giovannelli,1582-1625,1851-1876,0,0.00,False
40,Fino d'Arezzo,1292 and between the 13th and 14th century,1300-1322,0,0.00,False
41,Athanasius I,849-872,852-871,20,0.83,True
42,Luigi Messedaglia,1898-1956,1912-1929,18,0.31,True
43,Luca Gaurico,1501-1550,1505-1526,22,0.44,True
44,Maino De Maineri,around 1323 - 1364,1480-1507,0,0.00,False
45,Giovanni di Matera,around 1100-1110 to 1139,1106-1116,11,0.28,True
46,Bongiovanni da Cavriana,between the third and fifth decade of the 13th...,1270-1294,25,0.25,True
47,Armando Brasini,years around 1930,1907-1931,1,1.00,True
48,Giovanni Battista Abiosi,late 15th to early 16th century,1502-1523,22,0.22,True
49,Giuseppe Agnelli,1637-1703,1647-1683,37,0.55,True

## Accuracy of Cultura against Treccani

In [7]:
polity_rows = comparison[comparison["has_treccani_polity"]]
window_rows = comparison[comparison["has_treccani_window"]]
pd.DataFrame({
    "field": ["polity", "productivity window"],
    "correct": [polity_rows["polity_ok"].sum(), window_rows["window_ok"].sum()],
    "individuals": [len(polity_rows), len(window_rows)],
    "accuracy": [polity_rows["polity_ok"].mean().round(2), window_rows["window_ok"].mean().round(2)],
})

                 field  correct  individuals  accuracy
0               polity       37           49      0.76
1  productivity window       38           50      0.76