# Table X — Most notable individual per polity

20 famous polities, temporally dispersed from the 3rd millennium BCE to the 20th century CE.

**Source**: `data/humans_clean.duckdb` (read-only).

**Polity assignment**: `individuals_cliopatria` (Cliopatria polygon + temporal floruit match).

**Notability metric**: `individuals.notability_general` — the project's composite notability index, defined as the geometric mean of the western and non-western indices (each = Wikipedia editions in that bucket + metadata completeness + external identifiers from issuers in that bucket). Geometric mean rewards individuals with balanced cross-cultural reach and penalises one-sided fame. Computed by `scripts/_one_off/add_notability_indices.py` and `scripts/_one_off/redefine_notability_general_geomean.py`.

**Polity dates**: pulled from `polities_periods_cliopatria` (min `from_year`, max `to_year`) — never invented.

Output is a TSV printed at the end of the notebook (copy-paste manually).

In [1]:
from pathlib import Path
import duckdb
import pandas as pd

DB = Path('..') / 'data' / 'humans_clean.duckdb'
con = duckdb.connect(str(DB), read_only=True)
print('Connected to', DB.resolve())

Connected to /Users/charlesdedampierre/Desktop/Rsearch Folder/cultura_database/data/humans_clean.duckdb

In [2]:
# 20 famous polities, ordered chronologically.
# polity_id is the primary key in polities_cliopatria; polity names can
# collide so we always join on the integer ID.
POLITIES = [
    (6,    'Akkadian Empire'),
    (23,   'New Kingdom of Egypt'),
    (91,   'Achaemenid Empire'),
    (65,   'Macedonian Empire'),
    (93,   'Roman Republic'),
    (114,  'Ptolemaic Kingdom'),
    (204,  'Roman Empire'),
    (223,  'Sasanian Empire'),
    (366,  'Tang Dynasty'),
    (402,  'Carolingian Empire'),
    (414,  'Abbasid Caliphate'),
    (373,  'Byzantine Empire'),
    (729,  'Mongol Empire'),
    (397,  'Republic of Venice'),
    (523,  'Holy Roman Empire'),
    (896,  'Ming Dynasty'),
    (839,  'Ottoman Empire'),
    (1050, 'Tokugawa Shogunate'),
    (1117, 'Russian Empire'),
    (1102, 'Kingdom of Great Britain'),
]
len(POLITIES)

20

In [3]:
# Polity periods straight from the database — never invented.
polity_periods = con.execute(
    """
    SELECT polity_id,
           MIN(from_year) AS year_start,
           MAX(to_year)   AS year_end
    FROM polities_periods_cliopatria
    WHERE polity_id = ANY(?)
    GROUP BY polity_id
    """,
    [[pid for pid, _ in POLITIES]],
).fetchdf().set_index('polity_id')
polity_periods

           year_start  year_end
polity_id
6               -2300     -2101
23              -1500      -801
65               -675      -292
91               -550      -327
93               -500       -32
114              -331       -28
204               -31       394
223               215       643
366               623       910
373               633      1474
397               705      1796
402               718       989
414               750      1259
523               922      1806
729              1206      1293
839              1305      1923
896              1375      1644
1050             1600      1869
1102             1709      2024
1117             1721      1916

In [4]:
# For each polity, take the individual with the highest notability_general.
# individuals_cliopatria.polity_id is a ';'-joined string of polity IDs (one
# individual can be matched to several polities), so we split + list_contains.
def most_notable(polity_id: int):
    return con.execute(
        """
        SELECT i.wikidata_id,
               i.name_en,
               i.description_en,
               i.birthdate,
               i.deathdate,
               i.notability_general,
               i.notability_western,
               i.notability_non_western,
               i.wikimedia_links_count,
               ic.floruit_year
        FROM individuals_cliopatria ic
        JOIN individuals i USING(wikidata_id)
        WHERE list_contains(string_split(ic.polity_id, ';'), ?)
        ORDER BY i.notability_general DESC NULLS LAST
        LIMIT 1
        """,
        [str(polity_id)],
    ).fetchone()

rows = []
for pid, pname in POLITIES:
    r = most_notable(pid)
    period = polity_periods.loc[pid]
    rows.append({
        'polity_id': pid,
        'polity': pname,
        'year_start': int(period['year_start']),
        'year_end':   int(period['year_end']),
        'wikidata_id': r[0],
        'most_notable': r[1],
        'description': r[2],
        'birthdate': r[3],
        'deathdate': r[4],
        'notability_general':    r[5],
        'notability_western':    r[6],
        'notability_non_western':r[7],
        'wikipedia_languages':   r[8],
        'floruit_year': r[9],
    })

df = pd.DataFrame(rows).sort_values('year_start').reset_index(drop=True)
df

,polity_id,polity,year_start,year_end,wikidata_id,most_notable,description,birthdate,deathdate,notability_general,notability_western,notability_non_western,wikipedia_languages,floruit_year
0,6,Akkadian Empire,-2300,-2101,Q199461,Sargon of Akkad,founder of Akkadian Empire,-2350-01-01,-2300-01-01,45.497253,46,45,78,-2301
1,23,New Kingdom of Egypt,-1500,-801,Q12154,TutanKhamun,14th century BCE (18th dynasty) Egyptian pharaoh,-1340-01-01,-1323-01-01,72.828566,78,68,114,-1323
2,65,Macedonian Empire,-675,-292,Q8409,Alexander the Great,king of Macedonia and conqueror of Achaemenid ...,-0355-07-15,-0322-06-05,140.477756,138,143,259,-324
3,91,Achaemenid Empire,-550,-327,Q41155,Heraclitus,Greek philosopher (late 6th/early 5th-century BC),-0534-01-01,-0470-01-01,75.266194,103,55,144,-492
4,93,Roman Republic,-500,-32,Q1048,Julius Caesar,Roman general and dictator,-0099-07-01,-0043-03-13,150.598805,168,135,280,-57
5,114,Ptolemaic Kingdom,-331,-28,Q635,Cleopatra,queen of the Ptolemaic Kingdom of Egypt from 5...,-0068-01-11,-0029-08-10,100.349390,106,95,170,-34
6,204,Roman Empire,-31,394,Q302,Jesus Christ,central figure of Christianity (6 or 4 BC – AD...,-0005-01-01,0033-04-01,169.699735,154,187,341,29
7,223,Sasanian Empire,215,643,Q8467,Umar ibn Al-Khattāb,2nd Rashidun Caliph from 634 to 644,0586-01-01,0644-11-06,75.299402,63,90,150,628
8,366,Tang Dynasty,623,910,Q7071,Li Bai,Classical Chinese poet of the Tang dynasty (70...,0701-05-23,0762-12-04,103.489130,102,105,191,743
9,373,Byzantine Empire,633,1474,Q83100,Osman I,founder of the Ottoman Empire (died 1323/4),1258-08-30,1326-08-09,54.221767,49,60,103,1300
10,397,Republic of Venice,705,1796,Q6101,Marco Polo,Venetian explorer and merchant who travelled t...,1254-09-22,1324-01-16,130.938917,135,127,210,1296
11,402,Carolingian Empire,718,989,Q3044,Charlemagne,"king of Franks, regarded as the first Holy Rom...",0748-04-06,0814-02-01,116.884558,138,99,184,790
12,414,Abbasid Caliphate,750,1259,Q9038,Al-Khwarizmi,9th-century Persian mathematician and astronomer,0780-01-01,0850-01-01,92.913939,89,97,162,822
13,523,Holy Roman Empire,922,1806,Q5879,Johann Wolfgang von Goethe,"German writer, artist, natural scientist and p...",1749-08-28,1832-03-22,173.516570,193,156,274,1791
14,729,Mongol Empire,1206,1293,Q720,Genghis Khan,founder and first khan of the Mongol Empire (1...,1162-06-07,1227-09-01,116.275535,104,130,205,1204
15,839,Ottoman Empire,1305,1923,Q5152,Mustafa Kemal Atatürk,founding father of the Republic of Turkey (188...,1881-01-01,1938-11-10,138.455769,135,142,252,1923
16,896,Ming Dynasty,1375,1644,Q7333,Zheng He,"Chinese mariner, explorer, and diplomat",1371-01-01,1435-01-01,81.902381,78,86,148,1413
17,1050,Tokugawa Shogunate,1600,1869,Q5586,Katsushika Hokusai,Japanese artist (1760-1849),1760-10-31,1849-05-10,116.025859,127,106,173,1849
18,1102,Kingdom of Great Britain,1709,2024,Q8016,Winston Churchill,"British statesman, soldier and writer (1874–1965)",1874-11-30,1965-01-24,166.637331,178,156,257,1916
19,1117,Russian Empire,1721,1916,Q1394,Vladimir Lenin,founding leader of the Soviet Union from 1922 ...,1870-04-22,1924-01-21,163.996951,165,163,292,1912

## Helpers — period label & life-dates label

Display formatting only — values themselves come from the DB.

In [5]:
def fmt_year(y: int) -> str:
    if y is None:
        return ''
    return f'{abs(int(y))} BCE' if int(y) < 0 else f'{int(y)} CE'

def fmt_period(y0, y1) -> str:
    return f'{fmt_year(y0)} – {fmt_year(y1)}'

def parse_year(iso_date: str):
    if iso_date is None or iso_date == '' or str(iso_date).startswith('_:'):
        return None
    s = str(iso_date)
    sign = -1 if s.startswith('-') else 1
    body = s[1:] if s.startswith('-') else s
    try:
        return sign * int(body.split('-')[0])
    except Exception:
        return None

def fmt_lifespan(birth, death):
    by, dy = parse_year(birth), parse_year(death)
    if by is None and dy is None:
        return ''
    return f'{fmt_year(by) if by is not None else "?"} – {fmt_year(dy) if dy is not None else "?"}'

df['period']   = [fmt_period(s, e) for s, e in zip(df['year_start'], df['year_end'])]
df['lifespan'] = [fmt_lifespan(b, d) for b, d in zip(df['birthdate'], df['deathdate'])]
df[['polity', 'period', 'most_notable', 'lifespan', 'description',
    'notability_general', 'notability_western', 'notability_non_western',
    'wikipedia_languages']]

,polity,period,most_notable,lifespan,description,notability_general,notability_western,notability_non_western,wikipedia_languages
0,Akkadian Empire,2300 BCE – 2101 BCE,Sargon of Akkad,2350 BCE – 2300 BCE,founder of Akkadian Empire,45.497253,46,45,78
1,New Kingdom of Egypt,1500 BCE – 801 BCE,TutanKhamun,1340 BCE – 1323 BCE,14th century BCE (18th dynasty) Egyptian pharaoh,72.828566,78,68,114
2,Macedonian Empire,675 BCE – 292 BCE,Alexander the Great,355 BCE – 322 BCE,king of Macedonia and conqueror of Achaemenid ...,140.477756,138,143,259
3,Achaemenid Empire,550 BCE – 327 BCE,Heraclitus,534 BCE – 470 BCE,Greek philosopher (late 6th/early 5th-century BC),75.266194,103,55,144
4,Roman Republic,500 BCE – 32 BCE,Julius Caesar,99 BCE – 43 BCE,Roman general and dictator,150.598805,168,135,280
5,Ptolemaic Kingdom,331 BCE – 28 BCE,Cleopatra,68 BCE – 29 BCE,queen of the Ptolemaic Kingdom of Egypt from 5...,100.349390,106,95,170
6,Roman Empire,31 BCE – 394 CE,Jesus Christ,5 BCE – 33 CE,central figure of Christianity (6 or 4 BC – AD...,169.699735,154,187,341
7,Sasanian Empire,215 CE – 643 CE,Umar ibn Al-Khattāb,586 CE – 644 CE,2nd Rashidun Caliph from 634 to 644,75.299402,63,90,150
8,Tang Dynasty,623 CE – 910 CE,Li Bai,701 CE – 762 CE,Classical Chinese poet of the Tang dynasty (70...,103.489130,102,105,191
9,Byzantine Empire,633 CE – 1474 CE,Osman I,1258 CE – 1326 CE,founder of the Ottoman Empire (died 1323/4),54.221767,49,60,103
10,Republic of Venice,705 CE – 1796 CE,Marco Polo,1254 CE – 1324 CE,Venetian explorer and merchant who travelled t...,130.938917,135,127,210
11,Carolingian Empire,718 CE – 989 CE,Charlemagne,748 CE – 814 CE,"king of Franks, regarded as the first Holy Rom...",116.884558,138,99,184
12,Abbasid Caliphate,750 CE – 1259 CE,Al-Khwarizmi,780 CE – 850 CE,9th-century Persian mathematician and astronomer,92.913939,89,97,162
13,Holy Roman Empire,922 CE – 1806 CE,Johann Wolfgang von Goethe,1749 CE – 1832 CE,"German writer, artist, natural scientist and p...",173.516570,193,156,274
14,Mongol Empire,1206 CE – 1293 CE,Genghis Khan,1162 CE – 1227 CE,founder and first khan of the Mongol Empire (1...,116.275535,104,130,205
15,Ottoman Empire,1305 CE – 1923 CE,Mustafa Kemal Atatürk,1881 CE – 1938 CE,founding father of the Republic of Turkey (188...,138.455769,135,142,252
16,Ming Dynasty,1375 CE – 1644 CE,Zheng He,1371 CE – 1435 CE,"Chinese mariner, explorer, and diplomat",81.902381,78,86,148
17,Tokugawa Shogunate,1600 CE – 1869 CE,Katsushika Hokusai,1760 CE – 1849 CE,Japanese artist (1760-1849),116.025859,127,106,173
18,Kingdom of Great Britain,1709 CE – 2024 CE,Winston Churchill,1874 CE – 1965 CE,"British statesman, soldier and writer (1874–1965)",166.637331,178,156,257
19,Russian Empire,1721 CE – 1916 CE,Vladimir Lenin,1870 CE – 1924 CE,founding leader of the Soviet Union from 1922 ...,163.996951,165,163,292

## Table X — TSV (copy-paste)

Columns:

- **Polity** — name as it appears in `polities_cliopatria`.
- **Period** — `min(from_year) – max(to_year)` from `polities_periods_cliopatria`.
- **Most notable individual** — `argmax(notability_general)` over individuals matched to the polity in `individuals_cliopatria`.
- **Lifespan** — birth – death year from `individuals.birthdate` / `deathdate`.
- **Notability (general / W / NW)** — `notability_general`, `notability_western`, `notability_non_western` from `individuals`.
- **Wikipedia languages** — `wikimedia_links_count` (kept for reference).

In [6]:
tsv = df[[
    'polity',
    'period',
    'most_notable',
    'lifespan',
    'description',
    'notability_general',
    'notability_western',
    'notability_non_western',
    'wikipedia_languages',
]].rename(columns={
    'polity': 'Polity',
    'period': 'Period',
    'most_notable': 'Most notable individual',
    'lifespan': 'Lifespan',
    'description': 'Description',
    'notability_general':     'Notability (general)',
    'notability_western':     'Notability (W)',
    'notability_non_western': 'Notability (NW)',
    'wikipedia_languages':    'Wikipedia languages',
}).copy()
tsv['Notability (general)'] = tsv['Notability (general)'].round(1)
print(tsv.to_csv(sep='\t', index=False))

Polity	Period	Most notable individual	Lifespan	Description	Notability (general)	Notability (W)	Notability (NW)	Wikipedia languages
Akkadian Empire	2300 BCE – 2101 BCE	Sargon of Akkad	2350 BCE – 2300 BCE	founder of Akkadian Empire	45.5	46	45	78
New Kingdom of Egypt	1500 BCE – 801 BCE	TutanKhamun	1340 BCE – 1323 BCE	14th century BCE (18th dynasty) Egyptian pharaoh	72.8	78	68	114
Macedonian Empire	675 BCE – 292 BCE	Alexander the Great	355 BCE – 322 BCE	king of Macedonia and conqueror of Achaemenid Persia (356–323 BC)	140.5	138	143	259
Achaemenid Empire	550 BCE – 327 BCE	Heraclitus	534 BCE – 470 BCE	Greek philosopher (late 6th/early 5th-century BC)	75.3	103	55	144
Roman Republic	500 BCE – 32 BCE	Julius Caesar	99 BCE – 43 BCE	Roman general and dictator	150.6	168	135	280
Ptolemaic Kingdom	331 BCE – 28 BCE	Cleopatra	68 BCE – 29 BCE	queen of the Ptolemaic Kingdom of Egypt from 51 to 30 BCE	100.3	106	95	170
Roman Empire	31 BCE – 394 CE	Jesus Christ	5 BCE – 33 CE	central figure of Christianity (6 or 4 BC – AD 30 or 33)	169.7	154	187	341
Sasanian Empire	215 CE – 643 CE	Umar ibn Al-Khattāb	586 CE – 644 CE	2nd Rashidun Caliph from 634 to 644	75.3	63	90	150
Tang Dynasty	623 CE – 910 CE	Li Bai	701 CE – 762 CE	Classical Chinese poet of the Tang dynasty (701–762)	103.5	102	105	191
Byzantine Empire	633 CE – 1474 CE	Osman I	1258 CE – 1326 CE	founder of the Ottoman Empire (died 1323/4)	54.2	49	60	103
Republic of Venice	705 CE – 1796 CE	Marco Polo	1254 CE – 1324 CE	Venetian explorer and merchant who travelled through Asia (1254–1324)	130.9	135	127	210
Carolingian Empire	718 CE – 989 CE	Charlemagne	748 CE – 814 CE	king of Franks, regarded as the first Holy Roman Emperor (747–814)	116.9	138	99	184
Abbasid Caliphate	750 CE – 1259 CE	Al-Khwarizmi	780 CE – 850 CE	9th-century Persian mathematician and astronomer	92.9	89	97	162
Holy Roman Empire	922 CE – 1806 CE	Johann Wolfgang von Goethe	1749 CE – 1832 CE	German writer, artist, natural scientist and politician (1749–1832)	173.5	193	156	274
Mongol Empire	1206 CE – 1293 CE	Genghis Khan	1162 CE – 1227 CE	founder and first khan of the Mongol Empire (1162–1227)	116.3	104	130	205
Ottoman Empire	1305 CE – 1923 CE	Mustafa Kemal Atatürk	1881 CE – 1938 CE	founding father of the Republic of Turkey (1881–1938)	138.5	135	142	252
Ming Dynasty	1375 CE – 1644 CE	Zheng He	1371 CE – 1435 CE	Chinese mariner, explorer, and diplomat	81.9	78	86	148
Tokugawa Shogunate	1600 CE – 1869 CE	Katsushika Hokusai	1760 CE – 1849 CE	Japanese artist (1760-1849)	116.0	127	106	173
Kingdom of Great Britain	1709 CE – 2024 CE	Winston Churchill	1874 CE – 1965 CE	British statesman, soldier and writer (1874–1965)	166.6	178	156	257
Russian Empire	1721 CE – 1916 CE	Vladimir Lenin	1870 CE – 1924 CE	founding leader of the Soviet Union from 1922 to 1924 (1870–1924)	164.0	165	163	292